Master mdl 71574 54
catalyst/moodle-MDL-70329 pull request #137
Opened 2021-06-04 05:13 UTC by safatshahin

Pr for #54

2021-06-07 07:15 UTC, guillogo requested changes
Hi @safatshahin 

Review done.
Code checker: OK
Unit test: OK
User test: OK
Code: I've added 2 comments in order to add the TODO instead the debugging in qbank_chooser and qbank_chooser_item. Also, can you validate if the disable and enable validation in the scripts should be also done as we chatted for another plugin (delequestion).

Thank you.

2021-06-07 07:15 UTC, guillogo commented on question/classes/output/qbank_chooser.php
> +        debugging('Class qbank_chooser has been deprecated and moved to bank/editquestion,
Can you please comment this and add to a TODO in tracker: https://tracker.moodle.org/browse/MDL-71679

```
Class qbank_chooser has been deprecated and moved to bank/editquestion, please use qbank_editquestion\qbank_chooser instead.
line 57 of /question/classes/output/qbank_chooser.php: call to debugging()
line 106 of /question/classes/output/qbank_chooser.php: call to core_question\output\qbank_chooser->__construct()
line 1072 of /mod/quiz/classes/output/edit_renderer.php: call to core_question\output\qbank_chooser::get()
line 126 of /mod/quiz/classes/output/edit_renderer.php: call to mod_quiz\output\edit_renderer->question_chooser()
line 211 of /mod/quiz/edit.php: call to mod_quiz\output\edit_renderer->edit_page()
```

2021-06-07 07:15 UTC, guillogo commented on question/classes/output/qbank_chooser_item.php
> +        debugging('Class qbank_chooser_item has been deprecated and moved to bank/editquestion,
Can you please comment this and add to a TODO in tracker: https://tracker.moodle.org/browse/MDL-71679

Right now I'm getting a warning when editing a mod_quiz

```
Class qbank_chooser_item has been deprecated and moved to bank/editquestion, please use qbank_editquestion\qbank_chooser_item instead.
line 51 of /question/classes/output/qbank_chooser_item.php: call to debugging()
line 61 of /question/classes/output/qbank_chooser.php: call to core_question\output\qbank_chooser_item->__construct()
line ? of unknownfile: call to core_question\output\qbank_chooser->core_question\output\{closure}()
line 60 of /question/classes/output/qbank_chooser.php: call to array_map()
line 106 of /question/classes/output/qbank_chooser.php: call to core_question\output\qbank_chooser->__construct()
line 1072 of /mod/quiz/classes/output/edit_renderer.php: call to core_question\output\qbank_chooser::get()
line 126 of /mod/quiz/classes/output/edit_renderer.php: call to mod_quiz\output\edit_renderer->question_chooser()
line 211 of /mod/quiz/edit.php: call to mod_quiz\output\edit_renderer->edit_page()
```

2021-06-08 06:38 UTC, safatshahin commented
Hi @guillogo 
Made the changes as discussed, rebased with the latest helper class and called the method from the scripts.

2021-06-09 10:56 UTC, merged

2021-06-09 10:57 UTC, guillogo commented
Hi @safatshahin approved and merged. You can continue now with ready for tracker check list. Thank you.