Master mdl 71641 86
catalyst/moodle-MDL-70329 pull request #142
Opened 2021-06-08 04:47 UTC by safatshahin

PR for #86

2021-06-10 07:14 UTC, guillogo requested changes
Hi @safatshahin 

Review done:

User test: OK
Code checker: OK

To check:
1. Can we have a look to /tag/manage.php -> questions, should be this who handle the  enable or disable? we can check this tomorrow.
2. The js refactoring should include ES6 migration?
3. The external functions called in deprecated functions.

Thank you.

2021-06-11 02:36 UTC, safatshahin commented
Hi @guillogo 
Thanks for reviewing this, i have made the changes according to the review, regarding the points you mentioned:

1.    Can we have a look to /tag/manage.php -> questions, should be this who handle the enable or disable? we can check this tomorrow.  -> -- plugin enable and disable is something related to core which i think self dependent, but the view or the feature enable or disable should be handled by cfg->usertags, i have implemented that in the child class to act with this setting from moodle.
2.     The js refactoring should include ES6 migration? -- i dont think so, as we are just moving the js files to the appropriate location
3.     The external functions called in deprecated functions -- i was kinda thinking about it from different angles, but calling the correct one or not calling the correct one, wont make difference in this case, so removed the call.

Please let me know if you want any other changes.
Thanks

2021-06-11 06:12 UTC, guillogo commented on question/bank/tagquestion/db/services.php
> +);
In this line I'm getting this in codechecker: `#38: ); Line indented incorrectly; expected at least 4 spaces, found 0`

2021-06-11 06:13 UTC, guillogo commented
Hi @safatshahin thank you for your answers, just one more little change and is ready to be merged. Thank you.

2021-06-11 06:19 UTC, merged

2021-06-11 06:19 UTC, guillogo commented
Hi @safatshahin approved and merged. Thank you.