master_MDL-71585-58 Refactoring manage categories
catalyst/moodle-MDL-70329 pull request #163
Opened 2021-06-14 05:20 UTC by guillogo

PR:

1. Refactor manage categories.
2. Move unit test.
3. Add plugin navigation.

2021-06-15 03:11 UTC, safatshahin requested changes
Hi @guillogo 
Thank you for working in this. I have made the comments in the code.
Some points i wanted to mention:
1. Moving events from core to the plugin, there are some events exclusive to the plugin, also there are some tests in the plugin, related to those, whats your thoughts about moving them to the plugin?
2. Naming the test classes and also merging them: managecategories_test has got the tests which are related to category object, where category object has got a test file, question_category_object_test, i think those can be moved to one. questionlib_test should be named specific to this plugin as tests the helper methods, maybe like qbank_managecategories_helper_test or something related.

Thanks

2021-06-15 03:11 UTC, safatshahin commented on question/bank/managecategories/classes/question_category_object.php
> +    public function question_category_object($page, $pageurl, $contexts, $currentcat, $defaultcategory, $todelete, $addcontexts) {
do we need this deprecated one here? its already there in the old one and any legacy code is not pointing to this code.

2021-06-15 03:11 UTC, safatshahin commented on question/bank/managecategories/classes/question_category_object.php
> +        echo '<br />';
please use html_writer instead

2021-06-15 03:11 UTC, safatshahin commented on question/bank/managecategories/classes/question_category_object.php
> +        echo '<br />';
please use html_writer instead

2021-06-15 03:11 UTC, safatshahin commented on question/bank/managecategories/classes/form/question_category_edit_form.php
> +        if (question_is_only_child_of_top_category_in_context($currentcat)) {
please have a look at this function, looks like its exclusive to categories

2021-06-16 07:55 UTC, guillogo commented on mod/quiz/edit.php
> +use qbank_managecategories\question_category_object;
Removed, thank you Safat.

2021-06-16 09:39 UTC, guillogo commented on question/bank/managecategories/classes/question_category_list.php
> +        $this->records = get_categories_for_contexts($this->context->id, $this->sortby);
Done.

2021-06-16 11:11 UTC, guillogo commented on question/bank/managecategories/classes/question_category_list_item.php
> +        if ($category->parent && !question_is_only_child_of_top_category_in_context($category->id)) {
You're right. Moved:
question_is_only_child_of_top_category_in_context
question_is_top_category
question_can_delete_cat

2021-06-17 23:12 UTC, guillogo commented on question/bank/managecategories/classes/question_category_list_item.php
> +        return $item;
Thank you Safat, I've migrated the `html_writer::` code to a Mustache now.

2021-06-18 01:42 UTC, guillogo commented on question/bank/managecategories/classes/question_category_list.php
> +        $this->records = get_categories_for_contexts($this->context->id, $this->sortby);
function was moved. Thank you.

2021-06-18 01:42 UTC, guillogo commented on question/bank/managecategories/classes/question_category_list_item.php
> +        $questionbankurl = new moodle_url('/question/edit.php', $this->parentlist->pageurl->params());
Hi  Safat,

This is the list of functions that weren't moved as they are called by different places.


question_get_default_category
question_get_top_category
question_get_top_categories_for_contexts
question_make_default_categories
question_categorylist

Thank you.

2021-06-18 01:47 UTC, guillogo commented
Hi @safatshahin 

Thank you for reviewing, can you have a look again please. Done:

1. Refactor editlib.php functions.
2. Unit test merge.
3. Replace list item display with a template.
4. Refactor part of category functions in questionlib.php.
5. Get parent node via navigation lib.

These functions were'nt migrated as are called by different core parts. Can you please take a look if it is worth moving them by changing different parts in core:

- question_get_default_category
- question_get_top_category
- question_get_top_categories_for_contexts
- question_make_default_categories
- question_categorylist

Thank you,
Guillermo

2021-06-18 03:55 UTC, safatshahin commented
Hi @guillogo 
All good for now, there are some functions which seems that they're used in different places as you said, which seems like some fundamental functions not directly one, but lets keep it there for now.

2021-06-20 04:13 UTC, merged