PR for qbank comment
catalyst/moodle-MDL-70329 pull request #203
Opened 2021-07-16 04:33 UTC by safatshahin

2021-07-19 04:16 UTC, guillogo requested changes
Hi @safatshahin 

The PR has been reviewed. 

**Passed:**

- Feature test: OK
- User tests: Ok
- Capabilities test: OK (just thinking.. What do you think of the idea of having a deletecomment capability? to handle the possible loss of information)
- Unit test: OK
- Behat test: (has been added) running @core_question -> OK
- Code checker OK

**To fix:**
- Backup and restore: Getting this exception when try to restore a course that has comments on a question.
```
Exception - Call to undefined method restore_course_task::get_comment_mapping_itemname()
```
- Code: Some comments in the PR to check.


Thank you.
Guillermo

2021-07-19 04:36 UTC, safatshahin commented on question/bank/comment/lib.php
> + * @param stdClass $question
Actually, question_definition is a question object, and this method is used for a callback to the preview or any other plugin, the fragment is the only method using question definition from the question engine.

2021-07-19 04:49 UTC, safatshahin commented on question/bank/comment/classes/comment_count_column.php
> +    protected function display_content($question, $rowclasses): void {
it was a oneline <a> tag without any attribute, that's y didn't create a template for a line

2021-07-20 14:35 UTC, safatshahin commented
Hi @guillogo 
Thank you for your review of this. I have added some major codes to implement backup and restore in the core_backup which implements the backup and restore of comments for questions in course, quiz, or any other context system or categories. It also makes sure the question comment backup and restore is done with the question, not the regular comments XML structure.
Comment API has its own moodle/comment:delete capability which it checks in the interactive interface before triggering the delete from the js. It's a global feature from the API and I don't think there is anything can be done if we continue to use ajax based comments API. Hopefully, the comments API rebuild will do something good for this (there is a project that will start soon on that).
Please give it another go and let me know of any changes.
Cheers!

2021-07-22 06:37 UTC, safatshahin commented
Hi @guillogo 
I added the backup and restore with fixed issues in a new implementation, added deletion, behat tests and css fix.
Thanks

2021-07-23 04:32 UTC, guillogo approved these changes
Approved.

Tested all scenarios including backup and restore in a different ways.

2021-07-23 04:35 UTC, merged