Question history plugin
catalyst/moodle-MDL-70329 pull request #271
Opened 2021-08-22 09:32 UTC by safatshahin

2021-08-31 00:51 UTC, guillogo requested changes
Hi @safatshahin 

Thank you for working on this plugin, this is a very cool feature. I've finished the review just minors changes to do (added as a comments in the code).

Also, can you check these 2 things:

1. Should we need a behat test for the plugin?
2. Validate if history should be done as different tracker?

User test: Passed.

Gracias!

2021-08-31 00:51 UTC, guillogo commented on question/bank/history/templates/history_header.mustache
> +                {{{questionicon}}}
Please add it to the doc above. Thank you.

2021-08-31 00:51 UTC, guillogo commented on question/bank/history/history.php
> +// Todo: make changes after bulk actions ui MDL-72076.
Please use the `// TODO MDL-12345` Thank you.

2021-08-31 00:51 UTC, guillogo commented on question/bank/history/classes/question_history_view.php
> +                                        FROM {question_versions} v
Please align the query.

2021-08-31 00:51 UTC, guillogo commented on question/bank/history/history.php
> +
please add the enable/disable plugin validation here: `\core_question\local\bank\helper::require_plugin_enabled(...`

2021-09-24 03:20 UTC, safatshahin commented
closing for branching reason, creating a new one.

2021-09-24 03:20 UTC, closed without merging